### ISSUE TITLE
Magnet not found due to design change in 1337x.to

### ISSUE THREAD

**Issue by MichaelMeir** [Dentrax/GMDB#2]
1337x.to slightly changed the design where for the `doc.find(query)` does not work anymore
[Link to code](https://github.com/Dentrax/GMDB/blob/6b8de659c96073ba88ca1eb0d27f675e92c8e091/services/torrent/torrent1337x/parser.go#L105)
I've tried fixing it myself but for some reason the `go build` command wont update it
Heres the query i've tested on 1337x.to which works.
`body > main > div > div > div > div:nth-child(2) > div > ul > li > a`

**Comment by Dentrax** [comment]
Thanks! It has been fixed in https://github.com/Dentrax/GMDB/commit/df9038d0a7b1890bc8b949ae7da500c240cc1ce3 and i added a live test case in https://github.com/Dentrax/GMDB/commit/7208bf7b455d090b386eb8759fb9fe959dcd94f1.
